### ISSUE TITLE
Temporal Consistency of MRVSR

### ISSUE THREAD

**Issue by Magauiya** [bjmch/MRVSR#1]
Dear Mr. Benjamin, 

I would appreciate if you find time to answer following questions:

- Can you explain more about temporal profiling that is mentioned in the paper?
- Have you measured other temporal consistency metrics such as tLPIPS or difference in optical flow, etc. ?

Thank you!

**Comment by bjmch** [comment]
Hi,

Sorry for this late answer.

> Can you explain more about temporal profiling that is mentioned in the paper?

Temporal profiles are useful to assess temporal consistency of reconstructed videos. A temporal profile is produced by taking the same horizontal row of pixels from a number of successive frames in the video and stacking them vertically into a new image. Flickering artifacts in the video show up as jitter and jagged lines in the temporal profile. Sharper and less noisy temporal profile means less flickering artifacts i.e. better temporal consistency. 

> Have you measured other temporal consistency metrics such as tLPIPS or difference in optical flow, etc. ?

No, we did not measure such metrics. We did not measure other temporal consistency metrics.

I hope these answer your questions. Please do not hesitate if you have any further questions.

Best regards,

Benjamin

**Comment by Magauiya** [comment]
thank you!
